# Generated by Django 5.2.4 on 2025-08-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personaldetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(max_length=255)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('previous_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.DecimalField(decimal_places=1, max_digits=4)),
                ('joining_date', models.DateField()),
                ('branch', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_employment', to='personaldetails.personaldetails')),
            ],
        ),
    ]
