# Generated by Django 5.2.4 on 2025-08-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
