# Generated by Django 4.2 on 2025-08-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resign', '0002_resignation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='branch',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
