# Generated by Django 5.2.4 on 2025-08-01 10:49

import django.db.models.deletion
import multipleimages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personaldetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_uploads', to='personaldetails.personaldetails')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=multipleimages.models.upload_to)),
                ('document_type', models.CharField(choices=[('passport', 'Passport Size Photo'), ('aadhaar_front', 'Aadhaar Card Front'), ('aadhaar_back', 'Aadhaar Card Back'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID Card'), ('sslc', 'sslc Certificate'), ('plustwo', 'Plus Two Certificate'), ('ug', 'Undergraduate Certificate'), ('pg', 'Postgraduate Certificate'), ('experience', 'Experience Letter'), ('police_clearance', 'Police Clearance Certificate'), ('cibil_report', 'CIBIL Report')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='multipleimages.documentupload')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
