# Generated by Django 4.2 on 2025-08-04 07:39

from django.db import migrations, models
import multipleimages.models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleimages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.FileField(upload_to=multipleimages.models.upload_to),
        ),
    ]
